export const leadCategories: {
  [key in "Buyer" | "Seller"]: readonly string[];
} = {
  Buyer: [
    "new lead",
    "contacted",
    "needs consultation",
    "pre-approval in progress",
    "pre-approved",
    "property viewing scheduled",
    "viewed property",
    "actively searching",
    "offer made",
    "under negotiation",
    "closed deal",
    "cold lead",
    "lost lead",
  ] as const,

  Seller: [
    "new lead",
    "contacted",
    "needs valuation",
    "valuation report sent",
    "considering listing",
    "ready to list",
    "staging & photography",
    "property listed",
    "offer received",
    "under contract",
    "sold",
    "cold lead",
    "lost lead",
  ] as const,
};

// import { LeadType } from "../../lead/former-page";

export const dummyBuyerLeads: any[] = [
  {
    _id: "1",
    category: "Buyer",
    intent: "Buyer Guide",
    buyerProfile: "First-Time Buyer",
    status: "new lead",
    firstName: "James",
    lastName: "Okafor",
    email: "james.okafor@email.com",
    phone: "08012345678",
    source: "guide download",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "2",
    category: "Buyer",
    intent: "Mortgage Inquiry",
    buyerProfile: "First-Time Buyer",
    status: "needs consultation",
    firstName: "Aisha",
    lastName: "Bello",
    email: "aisha.bello@email.com",
    phone: "08023456789",
    source: "website form",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "3",
    category: "Buyer",
    intent: "House Tour",
    buyerProfile: "Repeat Buyer",
    status: "property viewing scheduled",
    firstName: "Michael",
    lastName: "Adeyemi",
    email: "michael.adeyemi@email.com",
    phone: "08034567890",
    propertyId: "property_123",
    source: "property page",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "4",
    category: "Buyer",
    intent: "House Tour",
    buyerProfile: "Investor",
    status: "viewed property",
    firstName: "Chinedu",
    lastName: "Okoye",
    email: "chinedu.okoye@email.com",
    phone: "08045678901",
    propertyId: "property_456",
    source: "listing inquiry",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "5",
    category: "Buyer",
    intent: "Mortgage Inquiry",
    buyerProfile: "Repeat Buyer",
    status: "pre-approved",
    firstName: "Fatima",
    lastName: "Sadiq",
    email: "fatima.sadiq@email.com",
    phone: "08056789012",
    source: "referral",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "6",
    category: "Buyer",
    intent: "House Tour",
    buyerProfile: "First-Time Buyer",
    status: "offer made",
    firstName: "Daniel",
    lastName: "Olawale",
    email: "daniel.olawale@email.com",
    phone: "08067890123",
    propertyId: "property_789",
    source: "agent referral",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "7",
    category: "Buyer",
    intent: "Mortgage Inquiry",
    buyerProfile: "Investor",
    status: "under negotiation",
    firstName: "Grace",
    lastName: "Uche",
    email: "grace.uche@email.com",
    phone: "08078901234",
    source: "campaign",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "8",
    category: "Buyer",
    intent: "House Tour",
    buyerProfile: "First-Time Buyer",
    status: "closed deal",
    firstName: "Samuel",
    lastName: "Ajayi",
    email: "samuel.ajayi@email.com",
    phone: "08089012345",
    propertyId: "property_999",
    source: "website form",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "9",
    category: "Buyer",
    intent: "Buyer Guide",
    buyerProfile: "First-Time Buyer",
    status: "contacted",
    firstName: "Zainab",
    lastName: "Lawal",
    email: "zainab.lawal@email.com",
    phone: "08090123456",
    source: "guide download",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "10",
    category: "Buyer",
    intent: "House Tour",
    buyerProfile: "Repeat Buyer",
    status: "lost lead",
    firstName: "Tunde",
    lastName: "Balogun",
    email: "tunde.balogun@email.com",
    phone: "08101234567",
    source: "listing inquiry",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

